### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mturiansky** [WatsonGroupTCD/J2suscep#1]
[_review for JOSS_](https://github.com/openjournals/joss-reviews/issues/2838)

Please provide installation instructions for your code. You should put this information in your wiki and clearly link to it in your README file. You should also clearly define the dependencies for this code.

From what I can glean, it needs a fortran compiler and LAPACK libraries? I would highly recommend including a single makefile (or some other compilation tool) at the base of your project, which compiles all the executables provided by the package.

**Comment by mfherbst** [comment]
I agree with @mturiansky.

I tried to compile your code (replacing `ifort` by `gfortran` in the Makefiles as I don't have the Intel compilers) and did still not succeed as GNU make bailed out with an error. You should make sure that your compilation routines work out of the box for reasonable systems. Setting up continuous integration with one of the options available at github is from my experience very good for this purpose.

**Comment by Swetanshu** [comment]
Installation instructions have been provided in the wiki now. A single makefile is required to compile and generate all the executables. The makefile takes in an include file that contains all the compiler specific options. An arch directory containing model include files for GNU and Intel compilers has also been included. Additionally, the blas options are also included in the model include files for different blas libraries.

**Comment by mturiansky** [comment]
Okay, the installation with GNU works for me now on my computer. You should delete the makefile.include in the src/ directory. It's a bit messy, and it distracted me from the fact that you provide clean and consistent makefile.include's in the src/arch/ directory.

@mfherbst if the installation works for you, feel free to close this issue.

**Comment by mfherbst** [comment]
Compilation works for me now.

**Comment by mfherbst** [comment]
(But I'm unable to close the issue, since I did not open it).
