### ISSUE TITLE
Difference / relation of J2suscep to other codes

### ISSUE THREAD

**Issue by mfherbst** [WatsonGroupTCD/J2suscep#10]
[review for JOSS](https://github.com/openjournals/joss-reviews/issues/2838)

In reading the JOSS paper it did not come across to me what the relationship / difference of J2suscep to other codes such as PHI and MAGPACK is. Especially PHI seems to be a pretty sophisticated code from what I capture. I would recommend that the authors improve on that section of the paper and strengthen the need for developing J2suscep.

**Comment by Swetanshu** [comment]
We already mention in the paper that the application covered by ej_calc is not implemented in any other code. We have included the suscep code, which shares some similarity with PHI and MAGPACK, to make the package self-contained.

**Comment by mfherbst** [comment]
I see your point, but I fail to see that being stated clearly and explicitly somewhere in the paper.

**Comment by Swetanshu** [comment]
@mfherbst 
We now mention the following in the paper: 

“To remove this dependency, more states can be modelled but this procedure results in a large number of solutions, that have to be averaged in some sensible way. Additionally, the problem of singular solutions also arises and such solutions need to be identified and removed. At the moment however, there is no convenient way to do so. The purpose of this package is to provide a means to accomplish this arduous task. Additionally, this package can also calculate the temperature dependence of magnetic susceptibility thereby enabling the comparison of the computational data to experiment. Although other codes like MAGPACK (Ramos et al., 2010) and PHI (Chilton et al., 2013) are available for the calculation of the mangnetic susceptibility, this package provides a one stop solution for the calculation of coupling constants and the determination of the magnetic susceptibility using these coupling constants.” (page 1, line 22 onwards).

Let me know if you want me to mention anything else.

**Comment by mfherbst** [comment]
I'm ok with the current version.

Notice however the typo "mangnetic susceptibility".
