### ISSUE TITLE
Authorship clarification for JOSS paper

### ISSUE THREAD

**Issue by dpsanders** [WatsonGroupTCD/J2suscep#12]
It seems that only @Swetanshu has contributed code to the repo.
Could you please clarify the contributions of the other two authors to the JOSS paper?

Part of [review for JOSS](https://github.com/openjournals/joss-reviews/issues/2838)

**Comment by Swetanshu** [comment]
Swetanshu wrote most of the code. Prof. G. W. Watson and Prof. W. Schmitt have contributed in the development of the theory implemented in the code and have supervised the development of the code. Prof. G. W. Watson also contributed in the code development, and created the makefiles and the tests.

**Comment by Swetanshu** [comment]
@dpsanders 
Let me know if you need any further information.

**Comment by dpsanders** [comment]
Thanks!
