### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mturiansky** [WatsonGroupTCD/J2suscep#2]
[_review for JOSS_](https://github.com/openjournals/joss-reviews/issues/2838)

Please include unit tests to ensure the proper operation of your code. In the present form, I see no way to actually validate that the results returned from the code are correct. (We always need to look out for those pesky factors of 2pi :smile:)

**Comment by mfherbst** [comment]
Again I agree with @mturiansky here. I would suggest using a simple example like the two-centre example suggested in #5 also for the purpose of unit testing as there the answer is probably easy to work out on pen and paper.

**Comment by dpsanders** [comment]
JOSS requires that there are tests, but they strictly do not need to be automated.
However, I agree that setting up continuous integration is key for modern software projects.

**Comment by Swetanshu** [comment]
Automated tests have been implemented. These tests, use the examples provided in the package and verify that the compiled codes generate results similar to those provided with the examples. As some of the examples take significantly longer to run compared to others, the tests have been implemented in a way that one can selectively run shorter and longer tests (details described in the installation instructions).

**Comment by mturiansky** [comment]
The tests (short and long) work for me, so I'm closing this.
