### ISSUE TITLE
formal vs. spin_dens

### ISSUE THREAD

**Issue by mturiansky** [WatsonGroupTCD/J2suscep#3]
[_review for JOSS_](https://github.com/openjournals/joss-reviews/issues/2838)

Please describe the difference between the `EJ_Calc/spin_dens` directory and the `EJ_Calc/formal/` directory. Are they different codes? A large amount of the code is reproduced between the two. This is bad coding practice. One should identify the subroutines that are needed for both codes and move them to a separate file, which can then be linked to both executables. Reproducing code is very bad from a maintainability point of view.

The differences between the two codes needs to be explained better. I was under the impression that `ej_calc` and `suscep` were the two codes provided by this repository.

**Comment by mfherbst** [comment]
As far as I can capture some details are [given in the wiki](https://github.com/WatsonGroupTCD/J2suscep/wiki/1c_basic_details), but I would also recommend to rethink the structure of the repository.

**Comment by Swetanshu** [comment]
The ej_calc code has been restructured to have a single source code. The compilation of the code produces two executables ej_calc_spin and ej_calc_form. The usage of both executables has been descibed in the wiki.

**Comment by mturiansky** [comment]
The structure looks a bit cleaner. I think this can be closed now.
