### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by mturiansky** [WatsonGroupTCD/J2suscep#4]
[_review for JOSS_](https://github.com/openjournals/joss-reviews/issues/2838)

Please consider adding a `CONTRIBUTING.md` file or a section in the wiki on how people should go about contributing to the code. I see that there is a section for developers, but it is mainly an overview of the code itself, rather than instructions and best practices for contributing.

**Comment by dpsanders** [comment]
This is a requirement for JOSS.

**Comment by Swetanshu** [comment]
A contributing page has been added in the wiki.

**Comment by mturiansky** [comment]
@dpsanders The contributing page in the wiki with the "for developers" sections looks like it covers the points. Does JOSS want an explicit contributing.md file or is the wiki sufficient?

**Comment by Swetanshu** [comment]
@mturiansky @dpsanders The contributing.md file has been added to the repo as well now.
