### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mturiansky** [WatsonGroupTCD/J2suscep#5]
[_review for JOSS_](https://github.com/openjournals/joss-reviews/issues/2838)

The example Mn complex is quite complex and has many degrees of freedom. It seems like a simpler system could be devised that would better illustrate how to use the code. I would imagine a two spin system with only one coupling constant should be feasible. (I understand that this doesn't show the major capability of the code of being able to sort out singular solutions and achieving some self-consistency, but I think it would be very useful for new users to see such an example.)

**Comment by mfherbst** [comment]
I agree and suggest that a simpler example or a few simpler examples, which could also serve very well as unit test cases.

**Comment by Swetanshu** [comment]
Simpler examples have been provided as part of the package. These examples have also been discussed in the wiki and are being used as test cases.
