### ISSUE TITLE
Continous Integration

### ISSUE THREAD

**Issue by mfherbst** [WatsonGroupTCD/J2suscep#8]
[review for JOSS](https://github.com/openjournals/joss-reviews/issues/2838)

Along the points mentioned in #5 and #2 I would strongly suggest to setup some form of continuous integration to automatically compile and test the code. I have found this an indispensable tool for maintaining longer-running research codes myself and can only recommend it.

**Comment by Swetanshu** [comment]
We have implemented automated tests for validating the code.

**Comment by mfherbst** [comment]
I just wanted to reiterate my point of setting up automatic continuous integration, which has not yet been achieved in the repo.

@dpsanders As far as I understand this is not required for JOSS, so I'd consider this optional as far as the review is concerned.

**Comment by dpsanders** [comment]
It is correct that continuous integration is not required for JOSS. But I do agree that it is key for modern software construction.

**Comment by Swetanshu** [comment]
@mfherbst @dpsanders 
Continuous integration is not straight forward for Fortran on github. We have included a test system to allow uses to test their installation. We will look at continuous integration in the future.
