### ISSUE TITLE
Example: Details about generation of data required for J2suscep

### ISSUE THREAD

**Issue by mfherbst** [WatsonGroupTCD/J2suscep#9]
[review for JOSS](https://github.com/openjournals/joss-reviews/issues/2838)

The required data for setting up J2suscep, namely results from population analysis / DFT energies etc. are in itself not always easy to obtain (especially for broken symmetry states). I think it would make the documentation more self-contained if the authors could link to manual sections of appropriate quantum-chemistry codes to do the calculations to detail the users how to produce such data. Even better the authors could provide a simple walked-through tutorial explaining exactly for one quantum chemistry code what calculations and input options have to be chosen to generate the data required for J2suscep.

**Comment by dpsanders** [comment]
+1 for a tutorial.

I had already requested a worked example in the pre-review.

**Comment by Swetanshu** [comment]
A walked-through tutorial for modelling the broken symmetry states using the Gaussian software has been provided in the documentation (see appendix).

**Comment by mfherbst** [comment]
Thanks, that's much better and satisfies me as far as the review is concerned. However, I'd recommend to directly link to the input files from the wiki such that they can be directly downloaded instead of manually searched in the repo.

**Comment by dpsanders** [comment]
@Swetanshu: Is there a complete example where I can do the entire calculation with only open-source software?

**Comment by Swetanshu** [comment]
@mfherbst  The input files are linked to the wiki now.
@dpsanders  We are aware that open source softwares like ORCA (https://orcaforum.kofo.mpg.de/app.php/portal) can perform such calculations but we don’t have much experience working with it. In principle you should be able to run the same example with ORCA and obtain a very similar or identical solution.

**Comment by mfherbst** [comment]
@Swetanshu Great. Thanks for adding the links and files. I'm happy now.

Just a short comment regarding @dpsanders question: ORCA is *not* open-source. It is free for academic use only.

Regarding open-source software, my first stop would be Psi4 or pyscf. I have never modelled these systems, so I might be missing something, but should these not be sufficient as well?

**Comment by mfherbst** [comment]
@dpsanders Feel free to close this once this is addressed from your end.

**Comment by Swetanshu** [comment]
@dpsanders @mfherbst Based on a quick search, it seems that the both Psi4 (https://psicode.org/psi4manual/master/scf.html#broken-symmetry) and pyscf (https://github.com/pyscf/pyscf/issues/538) can perform broken symmetry calculations and thus, can be used to calculate the coupling constants. However, we have no experience working with these codes.

**Comment by dpsanders** [comment]
@Swetanshu: Thanks for providing the worked example with Gaussian and the input files. Could you also add the instructions for actually running Gaussian with those input files, how to get the output from Gaussian and take that output and pass it to your tools? In other words, a *complete* worked example.

**Comment by dpsanders** [comment]
I feel like the worked example should not be in an appendix, but rather just another section in the documentation, called "Worked example" or similar.

**Comment by Swetanshu** [comment]
@dpsanders Details on running Gaussian and obtaining the necessary data has been added to the example. The example has also been moved to a section called "worked example".
